version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "api-birthday"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4jy3d5y927l5"
s3_prefix = "api-birthday"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ExecEnv=\"prod\" ApiBirthdayTableName=\"api-birthday\""
image_repositories = []
