version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::983913493830:user/aws-sam-cli-managed-stage-pipeline-re-PipelineUser-1CBUU4BK3R4D9"

[stage]
[stage.pipeline_bootstrap]
[stage.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::983913493830:role/aws-sam-cli-managed-stage-pi-PipelineExecutionRole-1QG9VT6ZII4WS"
cloudformation_execution_role = "arn:aws:iam::983913493830:role/aws-sam-cli-managed-stage-CloudFormationExecutionR-AT0OR74TDVG"
artifacts_bucket = "aws-sam-cli-managed-stage-pipelin-artifactsbucket-1bjs0y0g5t9d0"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::983913493830:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-1KOZKQF4XH75H"
cloudformation_execution_role = "arn:aws:iam::983913493830:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1RPS1T1LT4JNG"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-71x7izqb42p6"
image_repository = ""
region = "us-east-1"
