version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      # trigger the unit tests here
      - echo 'Running unit tests'
      - docker run -d -p 8000:8000 amazon/dynamodb-local
      - aws dynamodb create-table --table-name local \
        --attribute-definitions AttributeName=username,AttributeType=S \
        --key-schema AttributeName=username,KeyType=HASH \
        --provisioned-throughput ReadCapacityUnits=2,WriteCapacityUnits=2 \
        --endpoint-url=http://127.0.0.1:8000
      - pip install --no-cache-dir -r api_birthday/requirements.txt
      - pip install --no-cache-dir -r tests/requirements.txt
      - EXEC_ENV="local" REGION_NAME="local" TABLE_NAME="local" python3 -m pytest tests/unit -v
