version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      # trigger the integration tests here
      - echo 'Running integration tests'
      - python3 -m unittest discover -s tests/integration
